In [160]:
import numpy as np
import pandas as pd
scores=np.random.randint(60,100,size=(50,5))
students=pd.DataFrame(scores,index=range(1,51),columns=["國文","英文","數學","地理","歷史"])
students

    國文  英文  數學  地理  歷史
1   87  76  67  68  95
2   98  94  61  96  82
3   69  88  65  97  84
4   75  73  79  88  95
5   94  70  74  92  76
6   79  75  94  97  99
7   95  88  90  95  61
8   91  66  81  81  81
9   77  77  83  99  84
10  69  66  72  85  97
11  90  75  90  70  70
12  87  93  92  78  68
13  72  62  93  80  96
14  77  60  99  83  92
15  95  96  60  92  93
16  98  77  79  61  65
17  94  75  79  76  63
18  60  66  98  91  61
19  96  61  73  76  78
20  95  88  95  86  99
21  79  72  77  93  64
22  60  93  96  77  95
23  72  64  85  92  92
24  97  93  91  98  99
25  93  65  65  98  96
26  85  61  68  70  66
27  74  71  91  66  97
28  78  96  90  96  63
29  97  84  93  61  76
30  98  89  81  85  90
31  67  99  60  77  84
32  65  91  86  98  61
33  69  91  63  90  61
34  76  64  62  83  64
35  98  74  75  76  77
36  69  76  97  62  77
37  77  98  73  62  64
38  83  69  82  61  96
39  79  83  95  82  63
40  91  86  88  67  86
41  79  67  68  91  83
42  85  62  62  92  71
43  66  73  77  72  78
44  86  99  95  81  96
45  70  93  63  86  97
46  68  79  78  61  85
47  91  88  77  88  76
48  79  84  94  79  90
49  76  99  98  87  78
50  90  94  70  72  67

In [161]:
students[["國文","英文"]]

    國文  英文
1   87  76
2   98  94
3   69  88
4   75  73
5   94  70
6   79  75
7   95  88
8   91  66
9   77  77
10  69  66
11  90  75
12  87  93
13  72  62
14  77  60
15  95  96
16  98  77
17  94  75
18  60  66
19  96  61
20  95  88
21  79  72
22  60  93
23  72  64
24  97  93
25  93  65
26  85  61
27  74  71
28  78  96
29  97  84
30  98  89
31  67  99
32  65  91
33  69  91
34  76  64
35  98  74
36  69  76
37  77  98
38  83  69
39  79  83
40  91  86
41  79  67
42  85  62
43  66  73
44  86  99
45  70  93
46  68  79
47  91  88
48  79  84
49  76  99
50  90  94

In [162]:
students[0:3]

   國文  英文  數學  地理  歷史
1  87  76  67  68  95
2  98  94  61  96  82
3  69  88  65  97  84

In [163]:
students.loc[50],students.iloc[49]

(國文    90
 英文    94
 數學    70
 地理    72
 歷史    67
 Name: 50, dtype: int64,
 國文    90
 英文    94
 數學    70
 地理    72
 歷史    67
 Name: 50, dtype: int64)

In [164]:
students.loc[1:5],students.iloc[0:5]

(   國文  英文  數學  地理  歷史
 1  87  76  67  68  95
 2  98  94  61  96  82
 3  69  88  65  97  84
 4  75  73  79  88  95
 5  94  70  74  92  76,
    國文  英文  數學  地理  歷史
 1  87  76  67  68  95
 2  98  94  61  96  82
 3  69  88  65  97  84
 4  75  73  79  88  95
 5  94  70  74  92  76)

In [165]:
students["總分"]=students.sum(axis=1)
students['平均']=students.iloc[ : , :5].mean(axis=1)
students

    國文  英文  數學  地理  歷史   總分    平均
1   87  76  67  68  95  393  78.6
2   98  94  61  96  82  431  86.2
3   69  88  65  97  84  403  80.6
4   75  73  79  88  95  410  82.0
5   94  70  74  92  76  406  81.2
6   79  75  94  97  99  444  88.8
7   95  88  90  95  61  429  85.8
8   91  66  81  81  81  400  80.0
9   77  77  83  99  84  420  84.0
10  69  66  72  85  97  389  77.8
11  90  75  90  70  70  395  79.0
12  87  93  92  78  68  418  83.6
13  72  62  93  80  96  403  80.6
14  77  60  99  83  92  411  82.2
15  95  96  60  92  93  436  87.2
16  98  77  79  61  65  380  76.0
17  94  75  79  76  63  387  77.4
18  60  66  98  91  61  376  75.2
19  96  61  73  76  78  384  76.8
20  95  88  95  86  99  463  92.6
21  79  72  77  93  64  385  77.0
22  60  93  96  77  95  421  84.2
23  72  64  85  92  92  405  81.0
24  97  93  91  98  99  478  95.6
25  93  65  65  98  96  417  83.4
26  85  61  68  70  66  350  70.0
27  74  71  91  66  97  399  79.8
28  78  96  90  96  63  423  84.6
29  97  84  93  61  76  411  82.2
30  98  89  81  85  90  443  88.6
31  67  99  60  77  84  387  77.4
32  65  91  86  98  61  401  80.2
33  69  91  63  90  61  374  74.8
34  76  64  62  83  64  349  69.8
35  98  74  75  76  77  400  80.0
36  69  76  97  62  77  381  76.2
37  77  98  73  62  64  374  74.8
38  83  69  82  61  96  391  78.2
39  79  83  95  82  63  402  80.4
40  91  86  88  67  86  418  83.6
41  79  67  68  91  83  388  77.6
42  85  62  62  92  71  372  74.4
43  66  73  77  72  78  366  73.2
44  86  99  95  81  96  457  91.4
45  70  93  63  86  97  409  81.8
46  68  79  78  61  85  371  74.2
47  91  88  77  88  76  420  84.0
48  79  84  94  79  90  426  85.2
49  76  99  98  87  78  438  87.6
50  90  94  70  72  67  393  78.6

In [ ]:
students.to_csv("學生第一學期分數csv")

In [166]:
weather=pd.read_csv("最新的氣象預測.csv")
weather

,城市,起始時間,結束時間,最高溫度,最低溫度,感覺
0,臺北市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,29,悶熱
1,新北市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,29,悶熱
2,桃園市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,31,29,悶熱
3,臺中市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,31,29,悶熱
4,臺南市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,29,悶熱
5,高雄市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,29,悶熱
6,基隆市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,29,28,悶熱
7,新竹縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,32,30,悶熱
8,新竹市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,32,30,悶熱
9,苗栗縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,32,30,悶熱
10,彰化縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,31,29,悶熱
11,南投縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,28,舒適至悶熱
12,雲林縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,28,悶熱
13,嘉義縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,29,悶熱
14,嘉義市,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,30,27,舒適至悶熱
15,屏東縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,28,27,舒適至悶熱
16,宜蘭縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,29,28,悶熱
17,花蓮縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,29,28,悶熱
18,臺東縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,29,28,舒適至悶熱
19,澎湖縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,31,28,悶熱
20,金門縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,33,29,悶熱
21,連江縣,2023-09-03T12:00:00+08:00,2023-09-03T18:00:00+08:00,29,27,悶熱

In [11]:
pokemon="Rayquaza"
height=7
weight=206.5
bmi=weight/height**2
print(pokemon,str(height),weight)

Rayquaza 7 206.5