In [10]:
import numpy as np
import pandas as pd

df=pd.read_csv('學生第一學期分數.csv')
df1=df.rename(columns={'Unnamed: 0':'學號'})
df1

    學號  國文  英文  數學  地理  歷史   總分    平均
0    1  87  76  67  68  95  393  78.6
1    2  98  94  61  96  82  431  86.2
2    3  69  88  65  97  84  403  80.6
3    4  75  73  79  88  95  410  82.0
4    5  94  70  74  92  76  406  81.2
5    6  79  75  94  97  99  444  88.8
6    7  95  88  90  95  61  429  85.8
7    8  91  66  81  81  81  400  80.0
8    9  77  77  83  99  84  420  84.0
9   10  69  66  72  85  97  389  77.8
10  11  90  75  90  70  70  395  79.0
11  12  87  93  92  78  68  418  83.6
12  13  72  62  93  80  96  403  80.6
13  14  77  60  99  83  92  411  82.2
14  15  95  96  60  92  93  436  87.2
15  16  98  77  79  61  65  380  76.0
16  17  94  75  79  76  63  387  77.4
17  18  60  66  98  91  61  376  75.2
18  19  96  61  73  76  78  384  76.8
19  20  95  88  95  86  99  463  92.6
20  21  79  72  77  93  64  385  77.0
21  22  60  93  96  77  95  421  84.2
22  23  72  64  85  92  92  405  81.0
23  24  97  93  91  98  99  478  95.6
24  25  93  65  65  98  96  417  83.4
25  26  85  61  68  70  66  350  70.0
26  27  74  71  91  66  97  399  79.8
27  28  78  96  90  96  63  423  84.6
28  29  97  84  93  61  76  411  82.2
29  30  98  89  81  85  90  443  88.6
30  31  67  99  60  77  84  387  77.4
31  32  65  91  86  98  61  401  80.2
32  33  69  91  63  90  61  374  74.8
33  34  76  64  62  83  64  349  69.8
34  35  98  74  75  76  77  400  80.0
35  36  69  76  97  62  77  381  76.2
36  37  77  98  73  62  64  374  74.8
37  38  83  69  82  61  96  391  78.2
38  39  79  83  95  82  63  402  80.4
39  40  91  86  88  67  86  418  83.6
40  41  79  67  68  91  83  388  77.6
41  42  85  62  62  92  71  372  74.4
42  43  66  73  77  72  78  366  73.2
43  44  86  99  95  81  96  457  91.4
44  45  70  93  63  86  97  409  81.8
45  46  68  79  78  61  85  371  74.2
46  47  91  88  77  88  76  420  84.0
47  48  79  84  94  79  90  426  85.2
48  49  76  99  98  87  78  438  87.6
49  50  90  94  70  72  67  393  78.6

In [22]:
df1['排名']=df1['總分'].rank(ascending=False,method='min')
df2=df1.sort_values(by='排名')
df2

    學號  國文  英文  數學  地理  歷史   總分    平均    排名
23  24  97  93  91  98  99  478  95.6   1.0
19  20  95  88  95  86  99  463  92.6   2.0
43  44  86  99  95  81  96  457  91.4   3.0
5    6  79  75  94  97  99  444  88.8   4.0
29  30  98  89  81  85  90  443  88.6   5.0
48  49  76  99  98  87  78  438  87.6   6.0
14  15  95  96  60  92  93  436  87.2   7.0
1    2  98  94  61  96  82  431  86.2   8.0
6    7  95  88  90  95  61  429  85.8   9.0
47  48  79  84  94  79  90  426  85.2  10.0
27  28  78  96  90  96  63  423  84.6  11.0
21  22  60  93  96  77  95  421  84.2  12.0
46  47  91  88  77  88  76  420  84.0  13.0
8    9  77  77  83  99  84  420  84.0  13.0
11  12  87  93  92  78  68  418  83.6  15.0
39  40  91  86  88  67  86  418  83.6  15.0
24  25  93  65  65  98  96  417  83.4  17.0
13  14  77  60  99  83  92  411  82.2  18.0
28  29  97  84  93  61  76  411  82.2  18.0
3    4  75  73  79  88  95  410  82.0  20.0
44  45  70  93  63  86  97  409  81.8  21.0
4    5  94  70  74  92  76  406  81.2  22.0
22  23  72  64  85  92  92  405  81.0  23.0
12  13  72  62  93  80  96  403  80.6  24.0
2    3  69  88  65  97  84  403  80.6  24.0
38  39  79  83  95  82  63  402  80.4  26.0
31  32  65  91  86  98  61  401  80.2  27.0
7    8  91  66  81  81  81  400  80.0  28.0
34  35  98  74  75  76  77  400  80.0  28.0
26  27  74  71  91  66  97  399  79.8  30.0
10  11  90  75  90  70  70  395  79.0  31.0
0    1  87  76  67  68  95  393  78.6  32.0
49  50  90  94  70  72  67  393  78.6  32.0
37  38  83  69  82  61  96  391  78.2  34.0
9   10  69  66  72  85  97  389  77.8  35.0
40  41  79  67  68  91  83  388  77.6  36.0
30  31  67  99  60  77  84  387  77.4  37.0
16  17  94  75  79  76  63  387  77.4  37.0
20  21  79  72  77  93  64  385  77.0  39.0
18  19  96  61  73  76  78  384  76.8  40.0
35  36  69  76  97  62  77  381  76.2  41.0
15  16  98  77  79  61  65  380  76.0  42.0
17  18  60  66  98  91  61  376  75.2  43.0
36  37  77  98  73  62  64  374  74.8  44.0
32  33  69  91  63  90  61  374  74.8  44.0
41  42  85  62  62  92  71  372  74.4  46.0
45  46  68  79  78  61  85  371  74.2  47.0
42  43  66  73  77  72  78  366  73.2  48.0
25  26  85  61  68  70  66  350  70.0  49.0
33  34  76  64  62  83  64  349  69.8  50.0

In [26]:
display(df2.iloc[:5])
display(df2.iloc[-5:])
df2.to_excel('學生第一學期.xlsx')

    學號  國文  英文  數學  地理  歷史   總分    平均   排名
23  24  97  93  91  98  99  478  95.6  1.0
19  20  95  88  95  86  99  463  92.6  2.0
43  44  86  99  95  81  96  457  91.4  3.0
5    6  79  75  94  97  99  444  88.8  4.0
29  30  98  89  81  85  90  443  88.6  5.0

    學號  國文  英文  數學  地理  歷史   總分    平均    排名
41  42  85  62  62  92  71  372  74.4  46.0
45  46  68  79  78  61  85  371  74.2  47.0
42  43  66  73  77  72  78  366  73.2  48.0
25  26  85  61  68  70  66  350  70.0  49.0
33  34  76  64  62  83  64  349  69.8  50.0